### ISSUE TITLE
Controller uses cwd to locate template and parameter files

### ISSUE THREAD

**Issue by borsothy** [acquia/moonshot#104]
I bumped into this writing the backup plugin. What's basically happening is that if your working directory is not the project root, Moonshot simply gonna fail whatever you do. This is questionable in automated scenarios like builds, or using Moonshot without the CLI, which I believe is an actual concept. After a conversation with @glennpratt we figured a global config setting for the base path would be reasonable.

Reference: https://github.com/acquia/moonshot/blob/master/lib/moonshot/stack.rb#L162

**Comment by askreet** [comment]
In 0.8.x with the implementation of #89, we can do everything relative to the Moonfile.
