### ISSUE TITLE
Moonshot should expose the codedeploy flag to ignore ApplicationStop errors

### ISSUE THREAD

**Issue by pdrakeweb** [acquia/moonshot#105]
When a deployment goes out with a broken ApplicationStop configuration, it becomes impossible to release follow-up deployments.  CodeDeploy has a flag that can be set to ignore errors in ApplicationStop.  It would be nice if moonshot exposed this as an option so that deployments can continue.  See https://docs.aws.amazon.com/codedeploy/latest/userguide/troubleshooting.html#troubleshooting-deployments-applicationstop for more details.

**Comment by askreet** [comment]
What would the workflow be like for users? Run a deployment, it breaks, then run it again with --allow-stop-failures and it will possibly succeed?

**Comment by pdrakeweb** [comment]
Yes, that exactly.  Run deployment, it fails while stopping the service and halts the deployment.  Run again with --ignore-application-stop-failures and it fails while stopping the service but proceeds with the deployment.

**Comment by askreet** [comment]
I'd like to have this implemented in a way that allows mechanisms to add flags and hooks to the command interface. If someone was not using CodeDeploy, the --ignore-application-stop-failures option would not make sense.
