### ISSUE TITLE
Add support for YAML templates, released today.

### ISSUE THREAD

**Issue by askreet** [acquia/moonshot#130]
https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/

**Comment by gergelyborsothy** [comment]
@askreet I can get started with this one if you don't mind. Anything to discuss before I start implementing? I was thinking about some sort of pluggable mechanism for both JSON and YAML formats like parameter strategies are implemented. I think automatic detection of file formats would also be nice, so it works seamlessly, without even a command line option or such.

**Comment by askreet** [comment]
I think we have some features that just need to keep working. For example, plugins can call methods on Stack to see local parameters. Breaking each type of file into a class makes sense to me. Might make sense to use something where you make an instance of each class and ask it if the template source exists, ultimately failing of no valid source exacts. In the simple case, it would check for JSON, then YAML, then fail, but it would make extending this system possible. As you said, I wouldn't expect this to be something you'd set with an option in Moonshot::CLI.

Thanks for picking this up!

**Comment by gergelyborsothy** [comment]
> I think we have some features that just need to keep working.

Do tests existst to point the incompatibility out?

**Comment by askreet** [comment]
Fixed in #133
