### ISSUE TITLE
Add `moonshot init` to the CLI tool

### ISSUE THREAD

**Issue by borsothy** [acquia/moonshot#134]
Once we have #89 merged, I think it would be reasonable to have some sort of `moonshot init` or `moonshot new <app_name>` command. It could create all the directories and files necessary for Moonshot to function. It would make creating new applications easier, especially for new Moonshot users. Let me know what you think.

**Comment by askreet** [comment]
I think this is a good idea.

**Comment by borsothy** [comment]
@askreet is it okay if I get started with this one?

**Comment by askreet** [comment]
@borsothy By all means :)
