### ISSUE TITLE
Remove support for AWS_CREDENTIAL_FILE.

### ISSUE THREAD

**Issue by askreet** [acquia/moonshot#135]
This used to be required internally, but we removed this requirement in my project at least. AWS SDK no longer uses this file, so we shouldn't encourage deprecated credentials management.

Ping @pdrakeweb @glennpratt @borsothy @cpliakas @itafroma, do any of you rely on this behavior still. If so, any opposition to taking it out in 1.0.0 and updating your projects before upgrading?

**Comment by cpliakas** [comment]
@askreet Nope, not using it. Thanks for checking!

**Comment by itafroma** [comment]
Not using it, either!

**Comment by borsothy** [comment]
Not that I'm aware of.
