### ISSUE TITLE
Consider using Whirly.

### ISSUE THREAD

**Issue by Skarlso** [acquia/moonshot#140]
https://github.com/janlelis/whirly. Shiny, colorful. 

'nough said.

**Comment by borsothy** [comment]
I second this. @askreet do you like the idea of including this to 1.0?

**Comment by askreet** [comment]
It's neat but doesn't seem to offer the timing or success/failure features
I put into interactive-logger. Not sure it's a simple drop in or worth
blocking 1.0 on. If anything the next release of interactive-logger could
be based on it. I have some ideas for that as well.

**Comment by askreet** [comment]
This seems more appropriate as a change to interactive logger library, going to close this issue out.
