### ISSUE TITLE
RFC: Remove auto_prefix_stack and enforce <app_name>-<env_name> in Moonshot 1.0.0?

### ISSUE THREAD

**Issue by askreet** [acquia/moonshot#144]
Ping @glennpratt @pdrakeweb @itafroma @borsothy @cpliakas.

Very early on in moonshot (pre-open source) we supported passing "-n stack_name", where the stack name did not start with the application name. Then we added "auto_prefix_stack", defaulting to true.

I'm looking at implementing #99 and wondering if we can just make this enforced behavior. All Moonshot stacks are named [app_name]-[env_name], tagged moonshot_application=app_name and moonshot_environment=env_name.

Anyone out there relying on this ability to launch stacks with a non-conforming name?

**Comment by itafroma** [comment]
All of N3's stacks and docs use the standard naming convention, so we're not affected by this. Go for it!

**Comment by borsothy** [comment]
It's fine for the cloud-data team, although we explicitly set `auto_prefix_stack` to `true` on each CLI subclass, so l guess we just need to remove that in order to upgrade.

**Comment by glennpratt** [comment]
Sounds fine to me.

**Comment by cpliakas** [comment]
I'm good, everything that I have hooked up to Moonshot uses the standard naming convention.
