### ISSUE TITLE
Add the ability to reference a stack's outputs as parameters

### ISSUE THREAD

**Issue by cpliakas** [acquia/moonshot#187]
Exported outputs are cool, but they are global. I could be cool to be able to reference another stack's output in the parameters file, e.g. `MyParameter: {{some-stack:MyOutput}}`. This is not a high-priority feature by any stretch of the imagination, but I have a use case where this would help eliminate having to hunt down values that are exposed by other stacks where exported outputs are not a fit.

**Comment by askreet** [comment]
@cpliakas Have you looked at the [parent stack](http://moonshot.readthedocs.io/en/latest/user-guide/parent_stacks/) feature? We use it for exactly this purpose in a couple projects.

The docs could use some love, sorry about that.

**Comment by askreet** [comment]
For example, in one project we have a parent stack for networking and data persistence (RDS) services. In development, we all use the same parent stack, and production environments have their own dedicated parent stack.

With Moonshot 1.1 beta, you can do stuff like:

```
Moonshot.config do |c|
  # ...
  c.in_account 'mydevaccount' do |c|
    # No default for production, one must be specified or input parameters are missing.
    c.parent_stacks = ['default-networking-stack-thing']
  end
end
```

In dev:

    moonshot create -n mydevenv

In prod

    moonshot create -n prod-env --parent-stack prod-env-networking-stack

Of course, the networking stack is also a moonshot project ;-).

**Comment by cpliakas** [comment]
That's awesome! Can a parent have multiple children?

**Comment by askreet** [comment]
@cpliakas Yeah, the parent->child relationship isn't (currently) persisted after creation, it's just a mechanism for a stack create or update to copy Outputs from one stack as Parameters to another. In one project, we have hundreds of application stacks using the same resources from a networking and persistence stack.

**Comment by cpliakas** [comment]
Then it looks like this "feature" request is satisfied. Thanks for explaining, this sounds like it would solve my use case!
