### ISSUE TITLE
`list` command doesn't display actual name of the stack

### ISSUE THREAD

**Issue by Skarlso** [acquia/moonshot#203]
Funny story. `list` showed I had a stack running, which I needed to clean up. It told be `gb-xxxx` was `CREATE_COMPLETE`. 

However, when I searched for that stack, I couldn't find it. Because, turns out, cf dashboard's search doesn't support search by tag, as the rest of their services. At least not as seamlessly.

My stack-name was not that with which moonshot tagged my environment, thus, I couldn't find it. 

In `stack_lister.rb` here:

```ruby
          if app_tag && app_tag.value == @app_name
            p stack
            result <<
              EnvironmentDescription.new(env_tag.value, stack.creation_time, stack.stack_status)
          elsif legacy_tag && legacy_tag.value.start_with?(Moonshot.config.app_name)
            result <<
              EnvironmentDescription.new(legacy_tag.value, stack.creation_time, stack.stack_status)
          end
```

Name is `env_tag.value`, rather than `stack.stack_name`. Which would be the actual name of the stack for that tag making it easy to find the stack in question. Maybe include the environment tag value as a fourth option?

**Comment by askreet** [comment]
I think you were only able to hit this condition because you were actively developing on Moonshot and created a stack which didn't following the naming convention (app-name-env-name). For all other environments the list of environments should correlate to the CloudFormation Stack.

**Comment by Skarlso** [comment]
Yes, that could be. But wouldn't a typo in env-name still screw this up? The stack name wouldn't be the same if there is a miss type in either of them.

**Comment by Skarlso** [comment]
Actually my question would rather be, if there could be accidental mismatch between stackname and env.

**Comment by askreet** [comment]
I don't understand how that would happen with any released version of Moonshot. What are the steps to reproduce?

**Comment by Skarlso** [comment]
I have no idea how I did this. :-D Looking at the code this should not have been. I will try to reproduce my steps.

**Comment by askreet** [comment]
Let me know if you're able to reproduce this issue -- for now, I'll close the ticket.
