### ISSUE TITLE
Force rollout in order for it to work without SSH access.

### ISSUE THREAD

**Issue by Skarlso** [acquia/moonshot#211]
Rollout requires SSH connectivity to work. If people are trying to update their stack which has no access, but is given access with `moonshot update -P UserKeyPair bla`, this still needs a rollout in order to apply the key to an instance. But since there is no access, the rollout will fail.

Can we refactor the rollout so that it forces a terminate which in turn makes the ASG detach that instance and roll in a new one?

**Comment by askreet** [comment]
The default implementation of ASGRollout doesn't require any SSH access to the instance. There's a hook system you can use to define criteria such as PreDetach, TerminateWhen where we're using SSH internally. If you're wanting to skip those hooks, we could either:

- Add a `--skip-hooks` option here.
- Modify our hook code itself to support being bypassed.

I don't have a strong opinion on which direction we choose.

**Comment by Skarlso** [comment]
Let me get back to you on that once I have a free cycle.. :)

**Comment by askreet** [comment]
Closing this out for now, if we decide to go the `--skip-hooks` route or similar we can file a new issue.
