### ISSUE TITLE
Issue creating stacks in different regions on accounts where the services model is used

### ISSUE THREAD

**Issue by jamesiarmes** [acquia/moonshot#48]
<a href="https://github.com/cpliakas"><img src="https://avatars.githubusercontent.com/u/482722?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cpliakas](https://github.com/cpliakas)**
_Friday Jan 29, 2016 at 10:54 GMT_
_Originally opened as https://github.com/acquia/cloud-moonshot/issues/97_

---

My primary regions is `us-east-1`. Moonshot set up the `iam` stack, which was really helpful. The problem is that I am trying to create a stack in `eu-west-1`, and I get the following error:

```
bundle exec script/environment create -n ch-tests

OTP Code:  000000
Unable to determine ElevatedRole name by querying stack iam.
```

This is probably because it is looking for the stack in `us-east-1`, but since I am in the context of another region it cannot find it.

**Comment by askreet** [comment]
Closing this one out as it's related to an internal plugin we use for user management. I think it may be resolved, there, as well.
