### ISSUE TITLE
Add Ruby 2.3 to the travis file

### ISSUE THREAD

**Issue by jamesiarmes** [acquia/moonshot#52]
<a href="https://github.com/nickveenhof"><img src="https://avatars.githubusercontent.com/u/161341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nickveenhof](https://github.com/nickveenhof)**
_Wednesday Mar 09, 2016 at 19:53 GMT_
_Originally opened as https://github.com/acquia/cloud-moonshot/issues/116_

---

See title

**Comment by askreet** [comment]
This was resolved.
