### ISSUE TITLE
Add a basic cucumber test.

### ISSUE THREAD

**Issue by jamesiarmes** [acquia/moonshot#53]
<a href="https://github.com/glennpratt"><img src="https://avatars.githubusercontent.com/u/202230?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glennpratt](https://github.com/glennpratt)**
_Friday Feb 19, 2016 at 21:21 GMT_
_Originally opened as https://github.com/acquia/cloud-moonshot/pull/101_

----

Needs some thought on AWS calls.

----

_**[glennpratt](https://github.com/glennpratt)** included the following code: https://github.com/acquia/cloud-moonshot/pull/101/commits_

**Comment by jamesiarmes** [comment]
<a href="https://github.com/askreet"><img src="https://avatars.githubusercontent.com/u/662824?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [askreet](https://github.com/askreet)**
_Monday Feb 22, 2016 at 14:21 GMT_

----

Very cool. I don't know if we want these run as part of Travis as they get big though, a few actual stack up/down tests even with the simplest of CF templates is going to take minutes per example. Perhaps a nightly test run that reports to the Moonshot room in hipchat when it fails? (This would solve the creds issue too, since we can just import the ec2 creds and add them to the environment in Jenkins).

**Comment by jamesiarmes** [comment]
<a href="https://github.com/glennpratt"><img src="https://avatars.githubusercontent.com/u/202230?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [glennpratt](https://github.com/glennpratt)**
_Monday Feb 22, 2016 at 16:00 GMT_

----

Yeah, I'd add tags, `@slow`, `@aws_creds`, etc.

**Comment by jamesiarmes** [comment]
<a href="https://github.com/glennpratt"><img src="https://avatars.githubusercontent.com/u/202230?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [glennpratt](https://github.com/glennpratt)**
_Monday Feb 22, 2016 at 16:04 GMT_

----

https://nightli.es/

**Comment by glennpratt** [comment]
Superseded by #78
