### ISSUE TITLE
Create an ssh command

### ISSUE THREAD

**Issue by jamesiarmes** [acquia/moonshot#72]
<a href="https://github.com/glennpratt"><img src="https://avatars.githubusercontent.com/u/202230?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glennpratt](https://github.com/glennpratt)**
_Wednesday Mar 02, 2016 at 21:42 GMT_
_Originally opened as https://github.com/acquia/cloud-moonshot/issues/110_

----

Create a command to help ssh to a server in an ASG (interactive, maybe even parallel). Maybe some hooks for deployment dir or other things.

**Comment by askreet** [comment]
This was implemented back in #110. Woo!
