### ISSUE TITLE
Add a `console` command into core moonshot?

### ISSUE THREAD

**Issue by jamesiarmes** [acquia/moonshot#73]
<a href="https://github.com/askreet"><img src="https://avatars.githubusercontent.com/u/662824?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [askreet](https://github.com/askreet)**
_Wednesday Mar 02, 2016 at 18:46 GMT_
_Originally opened as https://github.com/acquia/cloud-moonshot/issues/109_

----

In hosting-api we have a custom method that allows us to drop to an interactive ruby shell with local variables set up for common Amazon services, which is handy because it's behind your credentials provider.

Example:
```ruby
desc :console, 'Launch a Pry console configured with AWS objects: ec2, iam, etc.'
def console
  # Calling controller sets up the Aws credentials provider.
  controller

  ec2 = Aws::EC2::Client.new
  iam = Aws::IAM::Client.new
  autoscaling = Aws::AutoScaling::Client.new
  cf = Aws::CloudFormation::Client.new

  Pry.start binding, backtrace: nil
end
```

**Comment by jamesiarmes** [comment]
<a href="https://github.com/glennpratt"><img src="https://avatars.githubusercontent.com/u/202230?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [glennpratt](https://github.com/glennpratt)**
_Wednesday Mar 02, 2016 at 21:40 GMT_

----

:+1:

**Comment by jamesiarmes** [comment]
<a href="https://github.com/codwazny"><img src="https://avatars.githubusercontent.com/u/1416716?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [codwazny](https://github.com/codwazny)**
_Monday Mar 07, 2016 at 18:35 GMT_

----

Are we worried at all about requiring 'pry'?

**Comment by jamesiarmes** [comment]
<a href="https://github.com/glennpratt"><img src="https://avatars.githubusercontent.com/u/202230?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [glennpratt](https://github.com/glennpratt)**
_Tuesday Mar 08, 2016 at 04:44 GMT_

----

It could be optional, like:

```ruby
begin
  require 'pry'
rescue LoadError
  warn 'Add pry to your development dependencies.'
  exit 1
end

**Comment by askreet** [comment]
Added in #139
