### ISSUE TITLE
All resources tagged with an "ah_stage" tag

### ISSUE THREAD

**Issue by aligentjim** [acquia/moonshot#99]
I've noticed that all of the resources created via Moonshot are tagged with an `ah_stage` tag.  The name of this tag and it's function aren't immediately obvious.  Is it required by Moonshot?  If so, could it be renamed to something more intuitive e.g. `moonshot_stack`?

**Comment by askreet** [comment]
This is an internal tag used by Acquia Hosting accounts to identify the purpose of resources. We missed it during our "make Moonshot open source" sprint :-(.

I think we should probably make the whole thing into an optional config setting defined at the `Moonshot::Controller` level.

**Comment by cpliakas** [comment]
+1, one nit-pick annoyance is that Amazon doesn't tag all resources with the `aws:cloudformation:stack-name` tag, i.e. with Kinesis streams, so it would actually be helpful to be able to set tags via Moonshot as it actually tags everything.

**Comment by glennpratt** [comment]
Does Moonshot tag everything? I thought it was just the stack, which then tags the resources it creates.

https://github.com/acquia/moonshot/blob/41f48f7e70170ec63c74cf7d9af5b945ac29fcb4/lib/moonshot/stack.rb#L249

**Comment by askreet** [comment]
@glennpratt You're correct, but where this helps @cpliakas and myself is that tagging an Auto-Scaling Group via CF tags causes it to tag it's instances. I don't believe the CF management tags make it down to the instances themselves. Could be wrong.

**Comment by cpliakas** [comment]
The `aws:` tags actually do go down to the instances in Autoscaling Groups. But some resources, like Kinesis, don't get the `aws:` tags when provisioned as a Resource via CloudFormation. It does get the `ah_stage` tag, though.

**Comment by glennpratt** [comment]
Thanks for the explanation.

**Comment by borsothy** [comment]
What shall we do about this? Make the key/value of the tag customizable?

**Comment by askreet** [comment]
@borsothy Yeah, with a moonshot-related default, like `moonshot_stack_name`. Internal projects that are concerned about compatibility will set it back to `ah_stage`.
